version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: go-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: snippetbox
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - my_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: goapptest
    ports:
      - "9000:9000"
    depends_on:
      - mysql
    networks:
      - my_network
    environment:
        user: "root"
        password: "root"
        app_port: 9000

networks:
  my_network: