name: Scan Main Branch

# Controls when the workflow will run
on:
  schedule:
    # Runs at 1:00 AM UTC every day
    - cron: '25 * * * *'
  push:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: main  # Ensure we're checking out the main branch
